#! /bin/sh

### BEGIN INIT INFO
# Provides:          scull, fauty and root modules
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Setup out of tree modules on boot
### END INIT INFO

KVER=$(uname -r)
MODLOC="/lib/modules/$KVER/extra"

case "$1" in

start)
echo "Starting init script for Module Loading"

## LOAD SCULL DRIVER
module="scull"
device="scull"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
echo "-> Load $module module, exit on failure"
insmod $MODLOC/$module.ko || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-3] 
chmod $mode  /dev/${device}[0-3]

rm -f /dev/${device}pipe[0-3]
mknod /dev/${device}pipe0 c $major 4
mknod /dev/${device}pipe1 c $major 5
mknod /dev/${device}pipe2 c $major 6
mknod /dev/${device}pipe3 c $major 7
ln -sf ${device}pipe0 /dev/${device}pipe
chgrp $group /dev/${device}pipe[0-3] 
chmod $mode  /dev/${device}pipe[0-3]

rm -f /dev/${device}single
mknod /dev/${device}single  c $major 8
chgrp $group /dev/${device}single
chmod $mode  /dev/${device}single

rm -f /dev/${device}uid
mknod /dev/${device}uid   c $major 9
chgrp $group /dev/${device}uid
chmod $mode  /dev/${device}uid

rm -f /dev/${device}wuid
mknod /dev/${device}wuid  c $major 10
chgrp $group /dev/${device}wuid
chmod $mode  /dev/${device}wuid

rm -f /dev/${device}priv
mknod /dev/${device}priv  c $major 11
chgrp $group /dev/${device}priv
chmod $mode  /dev/${device}priv

## LOAD FAULTY MODULE
module="faulty"
device="faulty"
mode="664"

echo "-> Load $module module, exit on failure"
insmod $MODLOC/$module.ko || exit 1

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
if [ ! -z ${major} ]; then
    echo "Remove any existing /dev node for /dev/${device}"
    rm -f /dev/${device}
    echo "Add a node for our device at /dev/${device} using mknod"
    mknod -m $mode /dev/${device} c $major 0
else
    echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
fi

## LOAD HELLO MODULE (modprobe not working in busybox. need to enable depmod in busybox menuconfig which is not possible in github actions)
module="hello"

echo "-> Load $module module, exit on failure"
insmod $MODLOC/$module.ko || exit 1

;;

stop)
echo "Removing user modules"

## UNLOAD SCULL DRIVER
module="scull"
device="scull"

# invoke rmmod with all arguments we got
echo "-> Unload $module module, exit on failure"
rmmod $module || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}[0-3] 
rm -f /dev/${device}priv
rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
rm -f /dev/${device}single
rm -f /dev/${device}uid
rm -f /dev/${device}wuid

## UNLOAD FAULTY MODULE
echo "-> Unload $module module, exit on failure"
module="faulty"
device="faulty"

# invoke rmmod with all arguments we got
rmmod $module || exit 1

# Remove stale nodes
rm -f /dev/${device}

## UNLOAD HELLO MODULE
module="hello"
echo "-> Unload $module module, exit on failure"
rmmod $module || exit 1

;;

*)
echo "Usage: $0 {start|stop}"
exit 1

esac

exit 0
